SRC := $(wildcard *.c)
OBJ := $(SRC:.c=.o)
TGT := libconnect-or-cut.dylib

CC      += -fno-common
CFLAGS  += -Wall -DMISSING_STRNDUP -DHAVE_GETPROGNAME

ifeq ($(stealth),1)
CFLAGS  += -DCOC_STEALTH
endif

.PHONY: all
all: $(TGT)

.PHONY: clean
clean:
	$(RM) $(OBJ) $(TGT)

$(TGT): $(OBJ)
	$(CC) -dynamiclib -flat_namespace -multiply_defined suppress -o $@ $< -ldl
